# Generated by Django 3.2.3 on 2021-05-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0018_auto_20210502_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='no', max_length=500, verbose_name='payment'),
        ),
    ]
